import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";

export default function Home() {
  const [msg, setMsg] = useState("");
  useEffect(() => {
    console.log("process", process);
    setMsg(`Hello from ${process.env.DB_HOST}`);
  }, []);

  const apiHanlder = async () => {
    const api = "/api/osv"; // Next.js - API Route: The `pages/api` directory is mapped to `/api/*`. Files in this directory are treated as API routes instead of React pages.
    const endpoint = "/querybatch";
    console.log("process", process);
    console.log("process.env", process.env);
    const response = await fetch(api, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        api: process.env.NEXT_API_BASEURL_OSV, // "https://api.osv.dev/v1",
        endpoint,
      },
      body: JSON.stringify({
        payload: [
          {
            package: {
              name: "next",
              ecosystem: "npm",
            },
            version: "13.5.6",
          },
          {
            package: {
              name: "rollup",
              ecosystem: "npm",
            },
            version: "4.9.6",
          },
          {
            package: {
              name: "vue",
              ecosystem: "npm",
            },
            version: "3.2.29",
          },
          {
            package: {
              name: "nanoid",
              ecosystem: "npm",
            },
            version: "3.3.7",
          },
          {
            package: {
              name: "vite",
              ecosystem: "npm",
            },
            version: "2.6.4",
          },
        ],
      }),
    });

    const data = await response.json();
    console.log(data);
    // console.log(JSON.parse(data).results);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button onClick={apiHanlder}>Fetch</button>
        <div>*** {msg}</div>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
